# 使用 Node.js 镜像
FROM node:16-alpine

# 设置工作目录
WORKDIR /app

# 复制静态服务器的 package.json 并安装依赖
COPY static_server/package*.json ./
RUN npm install

# 复制已构建好的 Flutter Web 应用
COPY build/web /app/build/web

# 复制服务器脚本
COPY static_server/server.js /app/server.js

# 暴露端口并启动服务器
EXPOSE 3000
CMD ["node", "server.js"]
