# 使用官方 OpenJDK 8 镜像作为基础镜像
FROM openjdk:8-jdk-alpine

# 设置工作目录
WORKDIR /app

# 将应用程序的 JAR 文件复制到容器中
COPY skating_system-0.0.1-SNAPSHOT.jar app.jar

# 暴露服务端口（与 application.yml 中的配置一致）
EXPOSE 44433

# 设置环境变量（可选，根据需要设置）
#ENV SPRING_PROFILES_ACTIVE=dev

# 启动 Spring Boot 应用程序
ENTRYPOINT ["java", "-jar", "app.jar"]
